### ISSUE TITLE
PDF support

### ISSUE THREAD

**Issue by Tomn94** [rascafr/eu-covid-qr-parser-demo#2]
Workaround: take a screenshot of the QR code in the PDF

**Comment by rascafr** [comment]
Actually, you can do it as well with `poppler-utils` package:

```bash
pdftocairo -png yourcertificate.pdf out
```

:)

**Comment by camillegroult** [comment]
Hi @rascafr and thanks to reply Im so sorry I was off from Git. Today playing around your project I think I found was is wrong or not working, If I read "new_gene_cert" in some App like "TousAntiCovid" french app and others It's not readeble I mean direclety I got a ErroR message like "Cert not readble" but just now using Swiss App or Belgium is working readable.
My question is how I we (you lol) can fix this issue bro @rascafr what do you think
