### ISSUE TITLE
Error: Ce certificat n'a pas été signé par une entité reconnue. kid: AA=='

### ISSUE THREAD

**Issue by lillois59** [rascafr/eu-covid-qr-parser-demo#3]
Hi @rascafr I'm still working on it since 72 hours non stop now, last nite I used mani android app to find my signature problem, this morning I found I think how to change param and its work on  : https://app.getcovidpass.eu/ also on their android app, work also in SpTH (spanish app), passchecker (dev : carrefour france), but still not regognize in sanipass.fr I got this error : 
**Error: Ce certificat n'a pas été signé par une entité reconnue. kid: AA=='**
**Error: This certificate was not signed by a recognized entity. kid: AA == '**

using this string -65535 value

whats do you thinks about @rascafr thanks a lot

**Comment by rascafr** [comment]
Hi @camillegroult
What's sanipass.fr? Seems like it's a bovine control website...

**Important reminder:** As mentionned in my repos (https://github.com/rascafr/eu-covid-qr-parser-demo#readme), you won't be able to sign a certificate if you don't have the private key...

**Comment by lillois59** [comment]
Hi @rascafr its sanipasse.fr sorry. I have a lot of question bro Im' still working on it and I can bypass some app but not all of them. 
For exemple in  :
GreenPass (android app by Ital innovation S.r.L) is okay
CheckDGC (android app) fail error : The cryptographic signature could not be verified NODSC
TAC verif (gouv.FR) readable but NON VALIDE


PS: petit details in some app my birthdate are wrong always in 04-01-1986 why ? lol

Also my question is if I got my private key where I use to filled in your script ?
64 bytes sequence health certificate signature (here) ?

Merci thanks a lot for you support @rascafr ask me whatever you want bro
ps : I bought my original HACKRF ONE + portapack from brainsharing, I will come back to you for lessons soon

**Comment by rascafr** [comment]
All dates in the payload uses the `DD-MM-YYYY` format.

Maybe you got that wrong in the `obj` js object, or I'll suggest you to contact the apps owners directly for support...

To sign a QR code using a private key *(that should not be publicly available...)*, I'd suggest to you refer to one of the repos I linked in the README, they got some examples in Node.js with the `cose-js` library

> https://github.com/ehn-dcc-development/ehn-sign-verify-javascript-trivial/blob/main/cose_sign.js#L38

**Comment by rascafr** [comment]
All dates in the payload uses the `YYYY-MM-DD` format, according to the specs below.

<img width="625" alt="Screenshot 2021-12-28 at 16 57 42" src="https://user-images.githubusercontent.com/12009083/147584211-a003306f-0009-4408-b176-7cb5f945472f.png">

Maybe you got that wrong in the `obj` js object, or I'll suggest you to contact the apps owners directly for support...

To sign a QR code using a private key *(that should not be publicly available...)*, I'd suggest to you refer to one of the repos I linked in the README, they got some examples in Node.js with the `cose-js` library

> https://github.com/ehn-dcc-development/ehn-sign-verify-javascript-trivial/blob/main/cose_sign.js#L38

**Comment by lillois59** [comment]
Hi, @rascafr I followed your advice and after lot of reading tonight about this topic  : 
2.2 Authentication and connection establishment ... I think is all about DCCG database and who have signed. Im confuse now because one month to work on it 🤪  

I have a new question now please, by reading this python-cwt.readthedocs.io I knew how to set parameters to get ECDSA w/ SHA-256 encryption (-7) okay, is for what Is look like a good Qrcode but the KeyId cannot verify by trusted KIDs database, so how I can sign my own certificate like : /C=FR/ST=FR/L=PARIS/O=BLABLA 
(if is possible) and how, adding something where ? or how I can sign or link ehn-sign-verify to eu-covid-qr-parser 

thanks 👍

**Comment by lillois59** [comment]
_Hi @rascafr and thanks for all you made for (us) me here was very benefic for me to try to do my best as freelance dev.
you can follow me here https://www.camillegroult.fr_ 

I'd like to keep you update about my rechearch first of all your project (code) is fully working well. And today in order to try again I registrer my self into IATA app just for try our New_Generated obvousily IATA dev are compiled their app with some GATEWAY to verify the key or signature the qrcode cn be accepted and updated into app when we select MONACO or ISRAEL and one island but not for alsmost All EU country whats does its means please @rascafr and how I can into your project link france-ehealth-certificates project cause I have a Node issue even I added to my folder or npm installed same issue see bellow plz ? 

.............................................................................................................................
const { pass2qr } = require("./lib/generator");
const { qr2pass } = require("./lib/extractor");
const { fhc } = require("./france-ehealth-certificaces");

node:internal/modules/cjs/loader:936
 throw err;
 ^Error: Cannot find module './france-ehealth-certificaces'
.............................................................................................................................

If you want and if is enough with my all issues we can close easy thanks @rascafr

**Comment by lillois59** [comment]
Hi @rascafr 

bypassed!

last ref : 
Note: FR has its own national list: https://ansm.sante.fr/dossiers-thematiques/covid-19-vaccins/covid-19-vaccins-autorises 
Note: DE, EL, IT, NL  and NO have not finalized their positions regarding the correspondence of vaccines for waiving travel restrictions 
Note: AT has not finalized their position regarding Covid-19 vaccine (recombinant) and R-COVI. However, Covishield is accepted for waiving travel restrictions
Note: DE has its own national list: http://www.pei.de/impfstoffe/covid-19

Was good these last weeks to work w/ project bro thanks 

stay tuned
